name: deploy to dev environment

on:
  push:
    branches:
      - main
      - staging
      - prod

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'dev' || github.ref_name }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: echo var
        run: echo ${{ vars.EXP_VALUE }}

      - name: echo var set in env
        run: echo $ENV_VAR
        env:
          ENV_VAR: ${{ vars.EXP_VALUE }}
