name: test matrix

on:
  push:
    branches:
      - main
      - staging
      - prod
  workflow_dispatch: # manual trigger

env:
  DEPLOY_STAGE: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}
  ENV_NAME: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}

jobs:
  deploy-first-phase:
    name: ${{ matrix.service }} deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}
    strategy:
      matrix:
        node-version: [16.15.0]
        service:
          - "service-base-1"
          - "service-base-2"
          - "service-base-3"
    steps:
      - name: echo service name
        run: echo ${{ matrix.service }}
      - name: echo environment name
        run: echo ${{ env.ENV_NAME }}
      - name: echo branch name
        run: echo ${{ github.ref_name }}

  deploy-second-phase:
    name: ${{ matrix.service }} deploy
    needs: deploy-first-phase
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}
    strategy:
      matrix:
        node-version: [16.15.0]
        service:
          - "service-one"
          - "service-two"
          - "service-three"
          - "service-four"
    steps:
      - name: echo service name
        run: echo ${{ matrix.service }}
      - name: echo environment name
        run: echo ${{ env.ENV_NAME }}
      - name: echo branch name
        run: echo ${{ github.ref_name }}

  post-deploy:
    name: post-deploy
    needs: [deploy-first-phase, deploy-second-phase]
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'prod' && 'prod' || github.ref_name == 'staging' && 'staging' || 'dev' }}
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
      - name: echo deploy stage
        run: echo $DEPLOY_STAGE
      - name: echo environment name
        run: echo ${{ env.ENV_NAME }}
      - name: echo branch name
        run: echo ${{ github.ref_name }}
